name: GraphPAR
channels:
  - pyg
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotli-python=1.0.9=py38h6a678d5_7
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.12.12=h06a4308_0
  - certifi=2023.11.17=py38h06a4308_0
  - cffi=1.16.0=py38h5eee18b_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=41.0.7=py38hdda0065_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.3.101=0
  - cuda-runtime=12.1.0=0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py38h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_3
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py38heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.4=py38h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.2=py38h06a4308_0
  - joblib=1.2.0=py38h06a4308_0
  - jpeg=9e=h5eee18b_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.8.1.2=0
  - libcurand=10.3.4.101=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.1=py38h7f8727e_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py38h5eee18b_1
  - mkl_fft=1.3.8=py38h5eee18b_0
  - mkl_random=1.2.4=py38hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py38h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py38h06a4308_0
  - numpy=1.24.3=py38hf6e8229_1
  - numpy-base=1.24.3=py38h060ed82_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.12=h7f8727e_0
  - pillow=10.0.1=py38ha6cbd5a_0
  - pip=23.3.1=py38h06a4308_0
  - platformdirs=3.10.0=py38h06a4308_0
  - pooch=1.7.0=py38h06a4308_0
  - psutil=5.9.0=py38h5eee18b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyg=2.4.0=py38_torch_2.1.0_cu121
  - pyopenssl=23.2.0=py38h06a4308_0
  - pyparsing=3.0.9=py38h06a4308_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.18=h955ad1f_0
  - pytorch=2.1.1=py3.8_cuda12.1_cudnn8.9.2_0
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.1=py38h5eee18b_0
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py38h06a4308_0
  - scikit-learn=1.3.0=py38h1128e8f_0
  - scipy=1.10.1=py38hf6e8229_1
  - setuptools=68.0.0=py38h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - sympy=1.12=py38h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=2.1.1=py38_cu121
  - torchtriton=2.1.0=py38
  - torchvision=0.16.1=py38_cu121
  - typing_extensions=4.7.1=py38h06a4308_0
  - urllib3=1.26.18=py38h06a4308_0
  - wheel=0.41.2=py38h06a4308_0
  - xz=5.4.5=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
    - absl-py==2.0.0
    - accelerate==0.25.0
    - aiohttp==3.9.1
    - aiosignal==1.3.1
    - alabaster==0.7.13
    - alembic==1.13.0
    - annotated-types==0.6.0
    - anyio==4.1.0
    - appdirs==1.4.4
    - asttokens==2.4.1
    - async-timeout==4.0.3
    - attrs==23.1.0
    - autopep8==2.0.4
    - babel==2.14.0
    - backcall==0.2.0
    - beautifulsoup4==4.12.2
    - bs4==0.0.1
    - cachetools==5.3.2
    - click==8.1.7
    - colorlog==6.8.0
    - comm==0.2.0
    - contourpy==1.1.1
    - cycler==0.12.1
    - dataclasses-json==0.6.3
    - debugpy==1.8.0
    - decorator==5.1.1
    - deeprobust==0.2.9
    - dgl==1.1.3+cu121
    - dglgo==0.0.2
    - distro==1.8.0
    - docker-pycreds==0.4.0
    - docutils==0.20.1
    - editdistance==0.6.2
    - exceptiongroup==1.2.0
    - executing==2.0.1
    - fonttools==4.46.0
    - frozenlist==1.4.1
    - fsspec==2023.12.2
    - gdown==4.7.3
    - gensim==3.8.3
    - gitdb==4.0.11
    - gitpython==3.1.41
    - google-ai-generativelanguage==0.1.0
    - google-api-core==2.15.0
    - google-auth==2.25.2
    - google-auth-oauthlib==1.0.0
    - google-generativeai==0.1.0rc1
    - googleapis-common-protos==1.62.0
    - greenlet==3.0.2
    - grpcio==1.60.0
    - grpcio-status==1.60.0
    - h11==0.14.0
    - h5py==3.10.0
    - httpcore==1.0.2
    - httpx==0.25.2
    - huggingface-hub==0.20.2
    - imageio==2.33.1
    - imagesize==1.4.1
    - importlib-metadata==7.0.0
    - importlib-resources==6.1.1
    - instructorembedding==1.0.1
    - ipdb==0.13.13
    - ipykernel==6.27.1
    - ipython==8.12.3
    - isort==5.13.2
    - jedi==0.19.1
    - jieba==0.42.1
    - jsonpatch==1.33
    - jsonpointer==2.4
    - jupyter-client==8.6.0
    - jupyter-core==5.5.0
    - kiwisolver==1.4.5
    - langchain==0.0.350
    - langchain-community==0.0.3
    - langchain-core==0.1.1
    - langsmith==0.0.71
    - lazy-loader==0.3
    - littleutils==0.2.2
    - llvmlite==0.41.1
    - loguru==0.7.2
    - mako==1.3.0
    - markdown==3.5.1
    - marshmallow==3.20.1
    - matplotlib==3.7.4
    - matplotlib-inline==0.1.6
    - multidict==6.0.4
    - mycolorpy==1.5.1
    - mypy-extensions==1.0.0
    - nest-asyncio==1.5.8
    - nltk==3.8.1
    - numba==0.58.1
    - numpydoc==1.6.0
    - oauthlib==3.2.2
    - ogb==1.3.6
    - openai==0.28.0
    - optuna==3.5.0
    - outdated==0.2.2
    - packaging==23.2
    - pandas==2.0.3
    - parso==0.8.3
    - patsy==0.5.6
    - pexpect==4.9.0
    - pickleshare==0.7.5
    - prompt-toolkit==3.0.43
    - proto-plus==1.23.0
    - protobuf==4.25.1
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyasn1==0.5.1
    - pyasn1-modules==0.3.0
    - pycodestyle==2.11.1
    - pydantic==2.5.2
    - pydantic-core==2.14.5
    - pygments==2.17.2
    - python-dateutil==2.8.2
    - pytorch-warmup==0.1.1
    - pytz==2023.3.post1
    - pywavelets==1.4.1
    - pyzmq==25.1.2
    - rdkit-pypi==2022.9.5
    - regex==2023.10.3
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - ruamel-yaml==0.18.5
    - ruamel-yaml-clib==0.2.8
    - safetensors==0.4.1
    - scikit-image==0.21.0
    - seaborn==0.13.0
    - sentence-transformers==2.2.2
    - sentencepiece==0.1.99
    - sentry-sdk==1.39.2
    - setproctitle==1.3.3
    - six==1.16.0
    - smart-open==6.4.0
    - smmap==5.0.1
    - sniffio==1.3.0
    - snowballstemmer==2.2.0
    - soupsieve==2.5
    - sphinx==7.1.2
    - sphinxcontrib-applehelp==1.0.4
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.1
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - sqlalchemy==2.0.23
    - stack-data==0.6.3
    - statsmodels==0.14.1
    - tabulate==0.9.0
    - tenacity==8.2.3
    - tensorboard==2.14.0
    - tensorboard-data-server==0.7.2
    - tensorboardx==2.6.2.2
    - texttable==1.7.0
    - tifffile==2023.7.10
    - tiktoken==0.5.2
    - tokenizers==0.15.0
    - tomli==2.0.1
    - torch-cluster==1.6.3
    - torch-scatter==2.1.2
    - torch-sparse==0.6.18
    - tornado==6.4
    - tqdm==4.66.2
    - traitlets==5.14.0
    - transformers==4.36.1
    - typer==0.9.0
    - typing-inspect==0.9.0
    - tzdata==2023.3
    - utils==1.0.2
    - wandb==0.16.2
    - wcwidth==0.2.12
    - werkzeug==3.0.1
    - yacs==0.1.8
    - yarl==1.9.4
    - zipp==3.17.0